-- 002_init_projects.sql
--
-- Phase 3: Project Registry tables.
--
-- Adds Project, Repo, Machine — the entities the-loom needs to know about
-- so every memory and telemetry event can be attributed to a known project
-- (and to one of its repos and one of its machines). Per the v3 platform
-- spec's "Project Registry" bounded context and the v2 roadmap Phase 3
-- ("every memory + telemetry event knows which Project, Repo, Machine it
-- came from").
--
-- Design choices:
--
--   1. `projects.id` is a UUID generated by the application (uuid_generate_v4
--      via pgcrypto's gen_random_uuid). The application controls IDs because
--      the discipline plugin needs to know the project_id BEFORE registering
--      (it gets created at `loom init` time, then sent through OTel as a
--      label on every hook event).
--
--   2. `projects.slug` is a human-readable identifier (e.g., "the-loom",
--      "make-skills"). UNIQUE per tenant. The slug is what the .env file's
--      LOOM_PROJECT_ID currently stores — registration upgrades it from
--      free-form string to FK reference.
--
--   3. `tenant_id` carried on every row so RLS applies the same isolation
--      envelope as the records table. Hosted-multi-tenant ready out of the
--      box; self-host falls back to the stable UUID per agent_context's
--      _resolve_tenant pattern.
--
--   4. `repos` and `machines` are CHILD tables of `projects` (FK ON DELETE
--      CASCADE) — a repo or machine without a project doesn't make sense,
--      and we want to be able to drop a project cleanly.
--
--   5. `machine_id` is the platform-level identifier (Windows HostName,
--      macOS hostname, etc.). The application detects it via
--      `socket.gethostname()` at `loom init`. A user with the same project
--      on two machines gets two `machines` rows but ONE `projects` row.
--
--   6. NO foreign key from `records.project_tags` to `projects.slug` —
--      project_tags is still a TEXT[] for flexibility (a memory can apply
--      to MULTIPLE projects). The Project Registry serves as the
--      authoritative list; the records table references by slug, not FK.
--      Phase 3 of v2 roadmap explicitly says "backfill stub Project for any
--      Phase 2 writes" — meaning existing free-form tags are still valid.
--
-- Idempotent: re-running this migration is safe (IF NOT EXISTS guards).

CREATE EXTENSION IF NOT EXISTS pgcrypto;  -- for gen_random_uuid()


-- ---------------------------------------------------------------------------
-- projects
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS projects (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug VARCHAR(128) NOT NULL,
  name VARCHAR(256) NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  -- kind: dev / archived / paused (per docs/proposals/2026-05-25-platform-data-model.md:17)
  -- 'dev' = actively worked. 'paused' = temporarily idle (skip from default lists
  -- but keep telemetry/memory references intact). 'archived' = done, hide from
  -- workflow but preserve history.
  kind VARCHAR(16) NOT NULL DEFAULT 'dev',
  tenant_id UUID NOT NULL,
  created_at DOUBLE PRECISION NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),
  archived_at DOUBLE PRECISION,
  extra JSONB NOT NULL DEFAULT '{}',
  CONSTRAINT projects_tenant_slug_unique UNIQUE (tenant_id, slug),
  CONSTRAINT projects_kind_check CHECK (kind IN ('dev', 'archived', 'paused'))
);

CREATE INDEX IF NOT EXISTS projects_tenant_idx ON projects (tenant_id);
CREATE INDEX IF NOT EXISTS projects_slug_idx ON projects (slug);
CREATE INDEX IF NOT EXISTS projects_extra_gin ON projects USING GIN (extra);


-- ---------------------------------------------------------------------------
-- repos (git repos belonging to a project; usually 1:1 but allows monorepo + multi-repo)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS repos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  url VARCHAR(512) NOT NULL,           -- e.g. https://github.com/owner/repo
  default_branch VARCHAR(128) NOT NULL DEFAULT 'main',
  tenant_id UUID NOT NULL,
  created_at DOUBLE PRECISION NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),
  CONSTRAINT repos_project_url_unique UNIQUE (project_id, url)
);

CREATE INDEX IF NOT EXISTS repos_project_idx ON repos (project_id);
CREATE INDEX IF NOT EXISTS repos_tenant_idx ON repos (tenant_id);


-- ---------------------------------------------------------------------------
-- machines (hosts where a project's code is checked out and worked on)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS machines (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  hostname VARCHAR(256) NOT NULL,      -- socket.gethostname()
  os VARCHAR(64) NOT NULL DEFAULT '',  -- 'windows', 'darwin', 'linux'
  checkout_path VARCHAR(1024) NOT NULL DEFAULT '',
  tenant_id UUID NOT NULL,
  created_at DOUBLE PRECISION NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),
  last_seen_at DOUBLE PRECISION NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),
  CONSTRAINT machines_project_host_unique UNIQUE (project_id, hostname)
);

CREATE INDEX IF NOT EXISTS machines_project_idx ON machines (project_id);
CREATE INDEX IF NOT EXISTS machines_tenant_idx ON machines (tenant_id);


-- ---------------------------------------------------------------------------
-- RLS — same envelope as records table
-- ---------------------------------------------------------------------------

ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE repos    ENABLE ROW LEVEL SECURITY;
ALTER TABLE machines ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS projects_tenant_isolation ON projects;
CREATE POLICY projects_tenant_isolation ON projects
  USING (tenant_id::text = current_setting('app.tenant_id', true));

DROP POLICY IF EXISTS repos_tenant_isolation ON repos;
CREATE POLICY repos_tenant_isolation ON repos
  USING (tenant_id::text = current_setting('app.tenant_id', true));

DROP POLICY IF EXISTS machines_tenant_isolation ON machines;
CREATE POLICY machines_tenant_isolation ON machines
  USING (tenant_id::text = current_setting('app.tenant_id', true));
