-- 004_init_policy.sql
--
-- Phase 5 of the recursive-skill engine: the Policy Service decisions slice.
-- Migrated from the-loom/infra/migrations/004_init_policy.sql (CORE DIRECTIVE 2).
--
-- ============================================================================
-- NUMBERING — kept at 004 (unlike candidates, which renumbered to 007)
-- ============================================================================
-- In the-loom this was 004_init_policy.sql. In Tapestry, slot 004 is FREE
-- (000/001/002/005/006/007 are taken; 003 and 004 were unused). Policy is a
-- SINGLE migration with no intermediate evolution to consolidate (unlike the
-- candidate schema, whose the-loom 003/005/006 collapsed into Tapestry 007), so
-- it keeps its original number. No renumber, no consolidation.
--
-- ============================================================================
-- LIVE-DB STATE — this migration is for PARITY / FRESH DEPLOYS
-- ============================================================================
-- The deployed service `loom-policy` (loom-policy.onrender.com, shipped
-- 2026-06-12) is LIVE against the shared loom-postgres. That live DB ALREADY
-- holds this exact table (the-loom's 004 created it; this file is byte-parity
-- with it). Running this file against the LIVE DB must therefore be a clean
-- no-op:
--   - CREATE TABLE IF NOT EXISTS       -> table exists -> skipped
--   - CREATE INDEX IF NOT EXISTS       -> indexes exist -> skipped
--   - ENABLE/FORCE ROW LEVEL SECURITY  -> idempotent
--   - DROP POLICY IF EXISTS + CREATE   -> re-creates identical policies
--
-- No ALTER COLUMN width fix is needed here (contrast 007's R1 fix): policy's
-- 004 is the ORIGINAL creation migration for policy_decisions — there is no
-- earlier, narrower version of any column in the live DB. decision_kind
-- VARCHAR(16) fits its longest value ('approve', 7 chars); target_status
-- VARCHAR(24) fits its longest ('promotion_requested', 19 chars).
--
-- GATE BEFORE CUTOVER: verify the live DB's policy_decisions column widths +
-- CHECK constraints + tenant continuity BEFORE repointing the Render service at
-- Tapestry. See services/policy/README.md "Cutover".
--
-- ## Cross-service id discipline (Pillar 0 / v3 ownership)
--
-- candidate_id is a UUID generated by services/architecture-registry/. We store
-- it but do NOT add a foreign key:
--   - Each bounded context owns its own data; FK across services would couple
--     deploy order and break the "candidates may be deleted but audit history
--     must survive" invariant.
--   - Cross-context joins happen at the read layer per
--     docs/proposals/2026-05-25-platform-data-model.md.
--
-- ## Two-mode commitment
--
-- Self-host: tenant_id resolves to SELF_HOST_TENANT_ID via auth_bridge
-- fallback. Hosted-multitenant: tenant_id from JWT claim. RLS policies enforce
-- isolation either way (same Pillar 0 pattern as candidates + records +
-- projects).
--
-- ## Schema choices
--
-- - CHECK constraints (NOT Postgres ENUMs). Matches the established convention.
--   ENUMs are harder to migrate when the value set evolves; CHECKs let us
--   evolve via DROP/CREATE constraint.
-- - target_status NULLABLE: 'hold' and 'demote' decisions may not name a target.
-- - decided_by VARCHAR — free-form ('operator' | 'system:auto' | 'agent:<kind>').
-- - extra JSONB — forward-compat slot.
-- - Per-tenant indexes match candidates' dominant access patterns.
--
-- ## Apply order
--
--   psql "$LOOM_DB_URL" -f 004_init_policy.sql
--   Depends on nothing but pgcrypto (defensively re-created below).
--
-- Idempotent: CREATE IF NOT EXISTS + DROP/CREATE POLICY pattern.

BEGIN;

-- pgcrypto exists from 002; defensive re-create for standalone apply
CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- ---------------------------------------------------------------------------
-- policy_decisions table
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS policy_decisions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- The candidate this decision applies to. UUID matches the candidates
  -- table's PK. NOT a foreign key — see header note on cross-service id
  -- discipline.
  candidate_id UUID NOT NULL,

  -- What KIND of decision:
  --   approve   = candidate is allowed to advance to target_status
  --   reject    = candidate is rejected (terminal-ish; can be overridden
  --               later by another approve decision)
  --   hold      = candidate is paused; target_status may be NULL
  --   demote    = candidate is being walked back; target_status names
  --               the new (lower or 'rejected') status
  decision_kind VARCHAR(16) NOT NULL,

  -- The candidate status this decision authorizes. NULLABLE for hold
  -- decisions (just pause; no specific target). Matches the same enum
  -- set as candidates.status CHECK (007_init_candidates.sql) for direct
  -- comparability.
  target_status VARCHAR(24),

  -- Operator-supplied rationale. Free-form. Persisted for auditability.
  reason TEXT NOT NULL DEFAULT '',

  -- WHO made the decision. Free-form for forward-compat with future
  -- agent kinds. Examples: 'operator', 'system:auto', 'agent:claude-code'.
  decided_by VARCHAR(128) NOT NULL DEFAULT 'operator',

  -- Epoch seconds (matches other tables' timestamp convention; see
  -- 002_init_projects.sql and 007_init_candidates.sql).
  decided_at DOUBLE PRECISION NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW()),

  -- Tenant envelope (Pillar 0). RLS reads current_setting('app.tenant_id').
  tenant_id UUID NOT NULL,

  -- Forward-compat slot — same role as records.extra + candidates.extra:
  -- {parent_decision_id, reviewed_by_chain, escalation_ref, ...} can
  -- evolve without schema migration.
  extra JSONB NOT NULL DEFAULT '{}',

  CONSTRAINT policy_decisions_kind_check CHECK (
    decision_kind IN ('approve', 'reject', 'hold', 'demote')
  ),
  CONSTRAINT policy_decisions_target_status_check CHECK (
    target_status IS NULL OR target_status IN (
      'draft', 'observed', 'recurring', 'stable',
      'promotion_requested', 'promoted', 'rejected'
    )
  )
);


-- ---------------------------------------------------------------------------
-- Indexes (dominant query patterns)
-- ---------------------------------------------------------------------------

-- "Show me ALL decisions for this candidate" — the policy-state aggregate.
CREATE INDEX IF NOT EXISTS policy_decisions_tenant_candidate_idx
  ON policy_decisions (tenant_id, candidate_id);

-- "Show me all approve / reject decisions" — operator audit views.
CREATE INDEX IF NOT EXISTS policy_decisions_tenant_kind_idx
  ON policy_decisions (tenant_id, decision_kind);

-- "Recent decisions first" — operator queue + audit listing.
CREATE INDEX IF NOT EXISTS policy_decisions_decided_at_idx
  ON policy_decisions (decided_at DESC);

-- GIN on extra for future containment queries
-- (e.g. WHERE extra @> '{"parent_decision_id":"X"}').
CREATE INDEX IF NOT EXISTS policy_decisions_extra_gin
  ON policy_decisions USING gin (extra jsonb_path_ops);


-- ---------------------------------------------------------------------------
-- Row-Level Security — same Pillar 0 pattern as candidates + projects
-- ---------------------------------------------------------------------------

ALTER TABLE policy_decisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE policy_decisions FORCE ROW LEVEL SECURITY;

-- Catch-all read policy. Service-role connections set app.tenant_id;
-- decisions are private-by-default.
DROP POLICY IF EXISTS policy_decisions_tenant_read ON policy_decisions;
CREATE POLICY policy_decisions_tenant_read ON policy_decisions
  FOR SELECT
  USING (
    tenant_id = COALESCE(
      NULLIF(current_setting('app.tenant_id', true), ''),
      '00000000-0000-0000-0000-000000000000'
    )::uuid
  );

DROP POLICY IF EXISTS policy_decisions_tenant_insert ON policy_decisions;
CREATE POLICY policy_decisions_tenant_insert ON policy_decisions
  FOR INSERT
  WITH CHECK (
    tenant_id = COALESCE(
      NULLIF(current_setting('app.tenant_id', true), ''),
      '00000000-0000-0000-0000-000000000000'
    )::uuid
  );

-- Decisions are immutable post-creation by design — audit trail integrity.
-- No UPDATE policy is defined; UPDATE attempts are rejected by RLS as
-- "policy violation". If a decision needs revision, file a NEW decision
-- that supersedes it (with extra.supersedes = <old_decision_id>).

DROP POLICY IF EXISTS policy_decisions_tenant_delete ON policy_decisions;
CREATE POLICY policy_decisions_tenant_delete ON policy_decisions
  FOR DELETE
  USING (
    tenant_id = COALESCE(
      NULLIF(current_setting('app.tenant_id', true), ''),
      '00000000-0000-0000-0000-000000000000'
    )::uuid
  );

-- Note: no UPDATE policy => UPDATEs fail with "policy violation". This is
-- the audit-immutability invariant. Test in test_policy_invariants.py.


COMMIT;
